{% set name = "keyrings.artifacts" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/keyrings_artifacts-{{ version }}.tar.gz
  sha256: d6368c6df12e9ab42aa6fe871bd545811429acd5d67e8abada68d4cc3ee4f034

build:
  entry_points:
    - keyring = keyring.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7
    - keyring >=16.0
    - requests >=2.20.0
    - azure-identity >=1.17.1
    - keyrings.alt >=5.0.0
    - pycryptodomex >=3.20.0
    - setuptools >=70.0.0,<76
test:
  imports:
    - keyrings_artifacts
  commands:
    - pip check
    - keyring --help
  requires:
    - pip

about:
  home: https://github.com/jslorrma/keyrings.artifacts
  summary: Keyring backend, that automatically retrieves credentials for Azure Artifacts.
  description: |
    The artifacts-keyring package provides authentication for publishing
    or consuming Python packages to or from Azure Artifacts feeds within Azure DevOps.
    This package is an extension to keyring, which will automatically find and use it once installed.
    Both pip and twine will use keyring to find credentials.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jslorrma
